version: '3.8'
services:
  server:
    build:
      dockerfile: server.Dockerfile
      context: ./
    container_name: wow_server
    ports:
      - "80:80"
    networks:
      - net
    env_file:
      - .env
  client:
    build:
      dockerfile: client.Dockerfile
      context: ./
    container_name: wow_client
    networks:
      - net
    env_file:
      - .env

networks:
  net:
    driver: bridge